name: tv-colour
channels:
  - conda-forge
dependencies:
  - aom=3.9.1
  - blinker=1.8.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - dav1d=1.2.1
  - double-conversion=3.3.0
  - expat=2.6.3
  - ffmpeg=6.1.2
  - flask=3.0.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf5=1.14.4
  - hpack=4.0.0
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imath=3.1.12
  - importlib-metadata=8.5.0
  - intel-openmp=2024.2.1
  - itsdangerous=2.2.0
  - jasper=4.2.4
  - jinja2=3.1.4
  - khronos-opencl-icd-loader=2024.05.08
  - krb5=1.21.3
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=19.1.0
  - libcurl=8.10.1
  - libdeflate=1.22
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libglib=2.82.1
  - libhwloc=2.11.1
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.10.0
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libpng=1.6.44
  - libprotobuf=5.27.5
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libwebp-base=1.4.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - markupsafe=2.1.5
  - mkl=2024.1.0
  - numpy=2.1.2
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.4.1
  - openssl=3.3.2
  - pcre2=10.44
  - pip=24.2
  - pixman=0.43.4
  - pthreads-win32=2.9.1
  - pugixml=1.14
  - py-opencv=4.10.0
  - pycparser=2.22
  - pyreadline3=3.5.4
  - pysocks=1.7.1
  - python=3.11.10
  - python_abi=3.11
  - qt6-main=6.7.3
  - requests=2.32.3
  - setuptools=75.1.0
  - snappy=1.2.1
  - svt-av1=2.2.1
  - tbb=2021.13.0
  - tk=8.6.13
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - werkzeug=3.0.4
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xz=5.2.6
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - plexapi==4.15.16
